---
- name: Configure banner on Cisco router
  hosts: ios_devices
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          ****************************************************
         * Welcome to Ansible AWX Tower Network Automation  *
         *                      Thank You                   *
         *    Aaqib Javaid Khan |TAC Engineer| CYBERNET     *
         ****************************************************
      register: banner_result

    - name: Print banner configuration result
      debug:
        var: banner_result
