---
- name: Configure the login banner
  hosts: ios
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Add configure the login banner
      ios_banner: 
        banner: login
        text: |
         ****************************************************
         *    Welcome to AWX Ansible Network Atomation      *
         *                     Thank You                    *
         *    Aaqib Javaid Khan |TAC Engineer| CYBERNET     *
         ****************************************************
        state: present 
    - name: save running to startup
      ios_config:
        save_when: modified                                                    
