---
- name: Configure the login banner
  hosts: ios
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Add login banner
      cisco.ios.ios_banner: 
       banner: login
       text: |
         ****************************************************
         *     Welcome to Ansible Network Automation        *
         *                     Thank You                    *
         *    Aaqib Javaid Khan |TAC Engineer| CYBERNET     *
         ****************************************************
       state: present 
    - name: save running to startup-config when modified
      cisco.ios.ios_config:
        save_when: modified                                                    
