---
- name: Configure the login banner
  hosts: ios_devices
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Add configure the login banner
      ios_banner: 
      
        banner: exec
        text: |
         ****************************************************
         * Welcome to Ansible AWX Tower Network Automation  *
         *                      Thank You                   *
         *    Aaqib Javaid Khan |TAC Engineer| CYBERNET     *
         ****************************************************
        state: present 
    - name: save running to start-config when modified
      ios_config:
        save_when: modified