---
- name: Configure the login banner
  hosts: iosxr
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Configure the login banner
      ios_banner: 
        banner: login
        text: |
         ****************************************************
         * Welcome to Ansible AWX Tower Network Automation  *
         *                      Thank You                   *
         *    Aaqib Javaid Khan |TAC Engineer| CYBERNET     *
         ****************************************************
        state: present 
    - name: save running to startup
      ios_config:
        save_when: modified
