---
- name: Create VLAN on Switches
  hosts: ios
  connection: network_cli
  gather_facts: false
  tasks:
#  - name: configure VLAN_ID
#    ios_config:
 #    lines:
  #     - vlan {{ vlan_id }}
  
  - name: Making Interface 
    ios_l2_interfaces:
      config:
      - name: Ethernet0/1
        trunk:
          allowed_vlans: 10,20,20,30,40
          native_vlan: 10
          encapsulation: dot1q
      state: merged       




